volumes:
  logs:
    driver: local

services:
  slim:
    image: php:8-alpine
    working_dir: /var/www
    command: php -S 0.0.0.0:8080 -t public
    ports:
      - "8080:8080"        
    volumes:
      - .:/var/www        

  db:
    image: mysql
    restart: always
    ports:
      - "3307:3306"       
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: toto

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 99:80
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=example